### DISCUSSION TITLE
How to add the Sonatype SNAPSHOT resolvers in a Bleep build?

### DISCUSSION THREAD

**Discussion by guizmaii** [oyvindberg/bleep#366] [Q&A] [answered]
In sbt, we'd do `ThisBuild / resolvers ++= Resolvers.sonatype("SNAPSHOT")`, how can we do the same with Bleep?

**Comment by oyvindberg** [comment, marked as answer]
Try to add this at the top-level of `bleep.yaml`:
```yaml
resolvers:
- type: maven
  uri: https://oss.sonatype.org/content/repositories/snapshots
  name: sonatype-snapshots
- type: maven
  uri: https://s01.oss.sonatype.org/content/repositories/snapshots
  name: sonatype-s01-snapshots
```

You're likely the first one to try snapshots, so report back if it works. I have always `publishLocal`ed the things I've been working on, so that's a workaround if it doesn't
