### ISSUE TITLE
idea: allow projects depend on scripts. 

### ISSUE THREAD

**Issue by oyvindberg** [oyvindberg/bleep#19]
This will allow us to do source generation and other shenanigans.

It should be relatively easy to implement actually, some tree traversal in the `bloop compile` command to find the commands, and then tell bloop to compile the necessary steps in turn

**Comment by oyvindberg** [comment]
So since I write this issue originally Bloop has gained the power of running source generators, see [this structure](https://github.com/scalacenter/bloop-config/blob/main/config/src/bloop/config/Config.scala#L260-L264).
I have not had the time to personally experiment with it.

If you can find a way to integrate with that it would be very cool indeed!

We'll need some kind of hint in the build, maybe something like this:
```yaml
projects:
  a:
    source-generator-scripts: gen-a-sources
scripts:
  gen-a-sources: ...
```
