### ISSUE TITLE
build: don't bake several values into a string

### ISSUE THREAD

**Issue by oyvindberg** [oyvindberg/bleep#227]
`jvm/name` contains both name and version
`scripts` contain both module and class name

**Comment by oyvindberg** [comment]
```diff
-  generate-docs: scripts/bleep.scripts.GenDocumentation
-  generate-resources: scripts-init/bleep.scripts.GenerateResources
-  generate-videos: scripts/bleep.scripts.GenDemoVideos
-  it: scripts/bleep.scripts.It
-  my-publish-local: scripts/bleep.scripts.PublishLocal
-  native-image: scripts/bleep.scripts.GenNativeImage
-  publish: scripts/bleep.scripts.Publish
+  generate-docs:
+    type: main,
+    project: scripts,
+    main: bleep.scripts.GenDocumentation
+  generate-resources:
+    type: main,
+    project: scripts,
+    main: scripts-init/bleep.scripts.GenerateResources
+  generate-videos:
+    type: main
+    project: scripts,
+    main: bleep.scripts.GenDemoVideos
+  it:
+    type: main
+    project: scripts,
+    main: bleep.scripts.It
+  my-publish-local:
+    type: main
+    project: scripts,
+    main: bleep.scripts.PublishLocal
+  native-image:
+    type: main
+    project: scripts,
+    main: bleep.scripts.GenNativeImage
+  publish:
+    type: main
+    project: scripts,
+    main: bleep.scripts.Publish
+  shell-test:
+    type: shell
+    command: "echo foo"
```
👎

**Comment by oyvindberg** [comment]
ideas:
- split into top-level `scripts:` and `scripts-shell:` to avoid `type` field and still provide good decoding messages, json schema help in IDE and so on
- hang `scripts` onto the project they are defined in, and have top-level scripts be shell scripts

**Comment by sideeffffect** [comment]
Why not just
```yaml
  generate-docs: { project: scripts, main: bleep.scripts.GenDocumentation }
```
?
Short, concise but still structured. YAML allows for having things on one line. And `type: main` seems to be the default, so no need to explicitly mention it.

**Comment by oyvindberg** [comment]
`type:main` as default seems very reasonable!

as for formatting I don't even know if we *can* override default formatting case by case. anyway I like that uniform all over, so not such a big fan of that.

After thinking about this a bit further I'm wondering if it's all that bad the way it is already, that is project and main put together in a string:

```yaml
scripts:
  format: myscripts/com.foo.RunScalaFmt
  npm: 
    type: shell
    command: npm install
```

maybe that's fine?

**Comment by sideeffffect** [comment]
Maybe we can also have `scripts` as the default project for scripts? 🤷 _Convention over configuration_ for the win! 💪😄

```yaml
scripts:
  format: com.foo.RunScalaFmt
  npm: 
    type: shell
    command: npm install
```

**Comment by oyvindberg** [comment]
Ok, I worked a bit more on it. I guess we can just drop the `type` altogether. errors will suffer a bit, but it's such a small structure that it can be hand-coded it at some later point.

```yaml
scripts:
  generate-docs:
    main: bleep.scripts.GenDocumentation
    project: scripts
  generate-resources:
    main: bleep.scripts.GenerateResources
    project: scripts-init
  generate-videos:
    main: bleep.scripts.GenDemoVideos
    project: scripts
  it:
    main: bleep.scripts.It
    project: scripts
  ls:
    command: ls -lah
    override-os:
      darwin: |
        cd bleep-core
        echo `pwd`
        ls -lah
      windows: dir
```

in the structure `ls` provides both `command` and `override-os` are optional, but bleep will error out if you try to run a script on an os where you have neither. `override-os` takes precedence
