### ISSUE TITLE
Documentation on authentication missing

### ISSUE THREAD

**Issue by kluen** [oyvindberg/bleep#255]
In order to use authentication for URLs configured in `resolvers`, one needs to create a config file. By looking through the code[^easy] I found that `https://github.com/dirs-dev/directories-jvm` is used and that on my macOS machine I had to create a `~/Library/Application Support/build.bleep.bleep/config.yaml` with the following contents:

```
authentications:
  <some-resolver-url>:
    user: <the-user>
    password: <the-password>

compileServerMode: 
  mode: shared
```

It would be great if this was documented on the website to lower the barrier for people trying out Bleep.

[^easy]: Btw. I found it relatively easy to do, thanks for the clean code base!

**Comment by oyvindberg** [comment]
Absolutely! linking this to #243 so I won't forget :)

**Comment by olivierdeckers** [comment]
The config file should not be put in ~/Library/Application Support/build.bleep/config.yaml

**Comment by oyvindberg** [comment]
@olivierdeckers hmm, WDYM shouldn't be put there?

I notice that the instructions at the top here have the old path pattern for the config file @ngbinh, you can run `bleep config file` to see the expected path on your system. might that have caused the problems you were seeing in #347 ?

**Comment by ngbinh** [comment]
@oyvindberg that's a good point. I will try it again today. But to make sure I get it right, do you have a fully working configuration? I am not sure if I should put the https part in the url and should I use double quotes on the user and password.

**Comment by oyvindberg** [comment]
```
authentications:
  https://artifactory.flaff.com:
    user: username
    password: password
```
