### ISSUE TITLE
Configuring `authentication` requires configuring `compileServerMode`

### ISSUE THREAD

**Issue by kluen** [oyvindberg/bleep#256]
When configuring authentication as described in #255, I had to include the setting `compileServerMode` to make the config valid. If I use only this as a `config.yaml`:
```
authentications:
  <some-resolver-url>:
    user: <the-user>
    password: <the-password>
```

I get:
```
📕 Couldn't parse json file /Users/kristof/Library/Application Support/build.bleep.bleep/config.yaml: Missing required field: DownField(compileServerMode)
```

I think it would be great if this config could somehow be merged with the defaults, so that it only needs to contain things that are changed by the user.
