### ISSUE TITLE
Composable builds! Import external builds

### ISSUE THREAD

**Issue by oyvindberg** [oyvindberg/bleep#264]
One of the earliest ideas which surfaced around the concept of a light-weight json-like build was that builds are now composable, and you can combine them however you want

## share templates within your organization
```yaml
imports:
  myorg: https://myorg/shared-templates/stable-sha
projects:
  a:
    extends: myorg.mytemplate
  scripts:
    dependsOn: myorg.scripts
```

this way you can standardize on dependency versions and all the shenanigans bigger orgs tend to do. You could also share scripts this way

## import external builds into your build

use case: mount multiple builds into your IDE so you can update them together seamlessly. This is incredibly useful for polyrepo programming.

Maybe something like this:

```yaml
imports:
  circe: https://github.com/circe/circe.git
projects:
  a:
    dependsOn: circe.circe-core
```

This would depend on either circe having a `bleep.yaml` already, or that bleep runs the automatic import. It's somewhat impractical to apply these changes to the build and ensure that they are not checked in, so I think it can be improved somewhat with

### build variants based on build rewrites

With the [proposed build variants idea](https://github.com/oyvindberg/bleep/issues/263) you can have your "normal" build with normal dependencies, and a build rewrite which rewrites dependencies into imports. Then you can use that build variant to compile, mount in IDE (`bleep setup-ide --build-variant inlined-deps jvm3`) and so on.

Given this build file
```yaml
build-variants:
  inlined-deps: scripts/InlineDeps
projects: 
  a:
    dependencies: io.circe::circe-core:1.4.0
    scala:
      version: 3.2.1
  scripts:
    dependencies: build.bleep::bleep-core:${BLEEP_VERSION}
    scala:
      version: 3.2.1
```

And this build rewrite (with hypothetical syntax):
```scala
package scripts
object InlineDeps extends bleep.InlineDepsRewrite {
  Map("io.circe" -> "https://github.com/circe/circe.git")
}
```
