### ISSUE TITLE
Bleep plugins

### ISSUE THREAD

**Issue by markehammons** [oyvindberg/bleep#333]
Right now, the way to add "plugins" to bleep seems to be the following behavior:

1. add a project named "plugins" or whatever you want to your bleep build
2. add the script/plugin as a dependency of plugins
3. In scripts, add a name for each plugin along with its main class

example: 
```yaml
projects: 
  plugins:
    dependencies:
      - fr.hammons::scoverage:0.0.0+1-93d77daa+20230629-1154-SNAPSHOT
    extends: template-base

scripts:
  scoverage-report: plugins/fr.hammons.bleep.scoverage.ScoverageReport
    
templates: 
  template-base: 
    platform: 
      name: jvm 
    scala: 
      version: 3.3.0
```

Is there some way we could streamline this a bit? Maybe have a plugins section that creates a "project" and "script" for each bleep plugin dependency?
