### ISSUE TITLE
Watch mode in `run` doesn't work with ZIO/ZIO-HTTP project

### ISSUE THREAD

**Issue by carlosedp** [oyvindberg/bleep#346]
Trying to use `bleep run httpserver -w` in my ZIO-HTTP sample project doesn't re-compile/re-run the project. 

Doing `bleep compile httpserver -w` works though.

To reproduce, clone https://github.com/carlosedp/bleepziohttp and run / compile with `-w`.

**Comment by carlosedp** [comment]
I've also tested with a Cask minimal HTTP project and same happens, watch mode in `run` doesn't reload.

Used files from https://github.com/com-lihaoyi/cask/tree/master/example/minimalApplication and the build below:

```yaml
$schema: https://raw.githubusercontent.com/oyvindberg/bleep/master/schema.json
$version: 0.0.2
jvm:
  name: graalvm-java17:22.3.1
projects:
  caskhttp:
    dependencies:
      - com.lihaoyi::cask:0.9.1
    extends: template-common
  tests:
    dependencies:
      - com.lihaoyi::utest:0.8.1
      - com.lihaoyi::requests:0.8.0
    dependsOn: caskhttp
    extends: template-common
    isTestProject: true
templates:
  template-common:
    platform:
      name: jvm
    scala:
      options: -encoding utf8 -feature -unchecked
      strict: true
      version: 3.3.0

```
