### ISSUE TITLE
Error showing binary incompatible libs

### ISSUE THREAD

**Issue by carlosedp** [oyvindberg/bleep#349]
I have a project using Mill that I'm planning to migrate to Bleep. I've ported all params but when I added my test project, I'm getting the following:

```
❯ bleep test
📙 Refreshing /Users/cdepaula/repos/chiselv/.bleep/builds/normal/.bloop...
📕 Error while loading build: Error resolving dependencies for toplevel-test: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:

        * com.lihaoyi:geny_2.13:1.0.0 (early-semver) is selected over 0.7.1
            +- com.lihaoyi:os-lib_2.13:0.9.1                      (depends on 1.0.0)
            +- com.lihaoyi:upickle-core_2.13:2.0.0                (depends on 0.7.1)
```

The project uses the exact same libs and versions from Mill project which works fine.

Here's my bleep.yaml:

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/oyvindberg/bleep/master/schema.json
$schema: https://raw.githubusercontent.com/oyvindberg/bleep/master/schema.json
$version: 0.0.2
jvm:
  name: temurin:1.17
projects:
  chiselv:
    extends: template-chisel
    platform:
      mainClass: chiselv.Toplevel
  chiselv-rvfi:
    extends: template-chisel
    folder: ./chiselv
    platform:
      mainClass: chiselv.RVFI
  toplevel-test:
    dependencies:
      - org.scalatest::scalatest:3.2.16
      - edu.berkeley.cs::chiseltest:5.0.0
      - com.carlosedp::riscvassembler:1.9.1
    dependsOn: chiselv
    folder: ./chiselv
    sources: ./test
    extends: template-common
    isTestProject: true
templates:
  template-common:
    platform:
      name: jvm
    source-layout: none
    scala:
      compilerPlugins: org.chipsalliance:::chisel-plugin:5.0.0
      options: -Ywarn-unused -deprecation -feature -unchecked -language:reflectiveCalls -Xcheckinit -Ywarn-dead-code -encoding UTF-8 -Xfatal-warnings -Ymacro-annotations
      version: 2.13.10
  template-chisel:
    extends: template-common
    sources: ./src
    resources: ./resources
    dependencies:
      - org.chipsalliance::chisel:5.0.0
      - com.lihaoyi::mainargs:0.5.1
```

And the Mill project:

```scala
import mill._, mill.scalalib._, mill.scalalib.publish._
import scalafmt._
import $ivy.`com.goyeau::mill-scalafix::0.3.1`
import com.goyeau.mill.scalafix.ScalafixModule
import $ivy.`com.carlosedp::mill-aliases::0.4.1`
import com.carlosedp.aliases._

object versions {
  val scala          = "2.13.10"
  val chisel         = "5.0.0"
  val chiseltest     = "5.0.0"
  val scalatest      = "3.2.16"
  val riscvassembler = "1.9.1"
  val mainargs       = "0.5.1"
}

trait BaseProject extends ScalaModule with ScalafixModule with ScalafmtModule {
  def scalaVersion = versions.scala
  def ivyDeps = Agg(
    ivy"org.chipsalliance::chisel:${versions.chisel}",
    ivy"com.lihaoyi::mainargs:${versions.mainargs}",
  )

  def scalacPluginIvyDeps = Agg(ivy"org.chipsalliance:::chisel-plugin:${versions.chisel}")

  object test extends ScalaTests with TestModule.ScalaTest {
    def ivyDeps = Agg(
      ivy"org.scalatest::scalatest:${versions.scalatest}",
      ivy"edu.berkeley.cs::chiseltest:${versions.chiseltest}",
      ivy"com.carlosedp::riscvassembler:${versions.riscvassembler}",
    )
  }

  override def scalacOptions = T {
    super.scalacOptions() ++ Seq(
      "-unchecked",
      "-deprecation",
      "-language:reflectiveCalls",
      "-encoding",
      "UTF-8",
      "-feature",
      "-Xcheckinit",
      "-Xfatal-warnings",
      "-Ywarn-dead-code",
      "-Ywarn-unused",
      "-Ymacro-annotations",
    )
  }
}

object chiselv extends BaseProject {
  def mainClass = Some("chiselv.Toplevel")
}
object chiselv_rvfi extends BaseProject {
  def mainClass = Some("chiselv.RVFI")
  def sources   = T.sources(millSourcePath / os.up / "chiselv" / "src")
}
```

Is there a way to "override" this binary error?

**Comment by oyvindberg** [comment]
Sorry, documentation is really lacking here. the solution is the same as in sbt really, as the code it lifted straight out of there. I have no idea if mill has incorporated this check yet

Anyway, this should do it:
```yaml
  toplevel-test:
    libraryVersionSchemes:
      com.lihaoyi::geny:always
```
