### ISSUE TITLE
Bleep's `build normalize` command removes comments from build file

### ISSUE THREAD

**Issue by carlosedp** [oyvindberg/bleep#350]
I have some comments in my build file, like:

```yaml
  httpserver-agent:
    # Use this project to generate graalvm native image metadata
    dependsOn: httpserver
    extends: template-common
    platform:
      jvmOptions: -agentlib:native-image-agent=config-merge-dir=httpserver/src/resources/META-INF/native-image
      mainClass: ZioHttpApp
```

But when I run `bleep build normalize`, the comment is removed. I also tried with the comment inlined with the project name but it also vanishes.

Would be nice if they could be kept as a kind of self-documenting feature.
