### ISSUE TITLE
Idea: Provide dependency management so that version numbers don't need to be repeated

### ISSUE THREAD

**Issue by DamianReeves** [oyvindberg/bleep#353]
It would be great if there was some sort of dependency management that allowed you to not have to specify version numbers for projects again.

If I have a build like:

```yaml
$schema: https://raw.githubusercontent.com/oyvindberg/bleep/master/schema.json
$version: 0.0.2
jvm:
  name: graalvm-java17:22.3.1
projects:
   proj1:
     dependencies: dev.zio::zio:2.0.16
  proj2:
    dependencies: 
   - dev.zio::zio::2.0.16
    - dev.zio::zio-streams::2.0.16
  proj3:
    dependencies: 
   - dev.zio::zio::2.0.16
    - dev.zio::zio-streams::2.0.16
```

Repeating the version numbers is both tedious and error prone.
