### ISSUE TITLE
Replace ${PROJECT_DIR} and similar in all parts of the config.

### ISSUE THREAD

**Issue by megri** [oyvindberg/bleep#362]
I am playing around with GraalVM 21 which is not yet available in the Coursier index.json. To work around this I've added a `oracle-index.json` at the project root with the contents
```
{
    "darwin": {
        "arm64": {
            "jdk@graalvm-java21": {
                "21": "tgz+https://download.oracle.com/graalvm/21/latest/graalvm-jdk-21_macos-aarch64_bin.tar.gz"
            }
        }
    }
}
```

I can use this index and platform with the following configuration
```
jvm:
  index: file:///Users/me/dev/my-sandbox-project/oracle-index.json
  name: graalvm-java21:21
…
```

It would be nice if I could instead use something like `index: file//${PROJECT_DIR}/oracle-index.json` to make it portable.
