### ISSUE TITLE
Running `sourcegen -w` doesn't re-trigger on changes in additional source directories

### ISSUE THREAD

**Issue by KaranAhlawat** [oyvindberg/bleep#389]
I have a Smithy project, for which I have written a codegen script. I have then added this script to the project where the Smithy sources reside, and running the codegen works fine.
Now, if I do `bleep sourcegen -w shared`, where `shared` is the project with the Smithy sources, it doesn't retrigger the codegen script when I change any of the smithy files, even though the the `smithy` folder is added as a source root in my `bleep.yaml`.

As show:
```yaml
  shared:
    dependencies:
      - com.disneystreaming.smithy4s::smithy4s-core:0.18.22
      - com.disneystreaming.alloy:alloy-core:0.3.8
    extends: template-common
    sources: ./src/smithy
    sourcegen:
      main: Smithy4sCodegen
      project: scripts
```

Not sure if I'm doing something wrong or missing a piece of configuration. Any help is appreciated :D
